config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  get 'subjects/index'
  get 'demo/hello'
  get 'pages/blog'
  get 'demo/escape_output'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord

  belongs_to :page, {:optional => false}
  has_many :section_edits
  has_many :admin_users, :through => :section_edits

  scope :visible, lambda {wehre(:visible => true)}
  scope :invisible, lambda {where(:visible => false)}
  scope :sorted, lambda {order("position ASC")}
  scope :newest_first, lambda {order("created_at DESC")}
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}

  CONTENT_TYPES = ['text', 'HTML']
  
  validates_presence_of :name
  validates_length_of :name, :maximum => 255
  validates_inclusion_of :content_type, :in => CONTENT_TYPES,
    :message => "must be one of: #{CONTENT_TYPES.join(', ')}"
  validates_presence_of :content

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  layout "admin"


  def index
    @sections = Section.sorted
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
    @section_count = Section.count + 1
    @pages = Page.sorted
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      flash[:notice] = "section saved successfully"
      redirect_to(sections_path)
    else
      @section_count = Section.count + 1
      @pages = Page.sorted
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
    @section_count = Section.count
    @pages = Page.sorted
  end

  def update
    @section = Section.find(params[:id])

    if @section.update_attributes(section_params)
      flash[:notice] = "Section updated successfully"
      redirect_to(sections_path(@section))
    else
      @section_count = Section.count
      @pages = Page.sorted
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
      flash[:notice] = "Section '#{@section.name}' destroyed successfully"
      redirect_to(sections_path)

  end

  private

  def section_params
    params.require(:section).permit(:page_id, :name, :position, :visible, :content_type, :content)
  end

end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Section form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>

  <tr>
    <th>Page id</th>
    <td><%= f.select(:page_id, @pages.map { |p| [p.name, p.id] }) %></td>
  </tr>

  <tr>
    <th> Position </th>
    <td> <%= f.select(:position, 1..@section_count) %></td>
  </tr>

  <tr>
    <th> Visible </th>
    <td><%= f.check_box(:visible) %></td>
  </tr>

  <tr>
    <th> Content type </th>
    <td>
      <%= f.radio_button(:content_type, 'text') %> Text
      <%= f.radio_button(:content_type, 'HTML') %> HTML

    </td>
  </tr>

  <tr>
    <th> Content </th>
    <td> <%= f.text_area(:content, :size => '40x10') %> </td>
  </tr>

</table>

app/views/sections/delete.html.erb
<%= link_to("<<< Back to Sections list", sections_path, :class => "back-link") %>

<div class="Section delete">
  <h2>Delete Section </h2>

  <%= form_for(@section, :method => 'delete') do |f| %>

    <p> Are you sure you want to permanently delete this section? </p>

    <p class="reference-name"><%= "Section: \"#{f.object.name}\" " %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Section") %>
    </div>

  <% end %>

</div>

app/views/sections/edit.html.erb
<b>
<%= link_to("<<< Back to list", sections_path, :class => "back-link") %>
</b>

<div class="sections edit">
  <h2> Create Section </h2>

  <%= form_for(@section) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f})
  <div class="form-buttons">
    <%= f.submit("Update Section") %>
  </div>

  <% end %>

</div>

app/views/sections/index.html.erb
<% if !flash[:notice].blank? %>
<div class ="flash notice">
  <%= flash[:notice] %>
</div>
<%end%>

<%= link_to('<< back to pages', pages_path, :class => 'back-link')%>
<div class ="Sections index">
  <h2> Sections </h2>

  <%= link_to("Create new Section", new_section_path, :class => 'action new') %>

    <table class ='list' summary ='sections list'>
    <tr class ="header">
      <th> # </th>
      <th> Page ID </th>
      <th> Name </th>
      <th> Visible </th>
      <th> Content Type </th>
      <th> Actions </th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      <td> <%= section.position %> </td>
      <td> <%= section.page_id %> </td>
      <td> <%= section.name %> </td>
      <td class ='center'> <%= section.visible ? 'Yes' : 'No' %> </td>
      <td class ='center'> <%= section.content_type %> </td>
      <td class ='actions'>
        <%= link_to("Show", section_path(section), :class => 'action show') %>
        <%= link_to("Edit", edit_section_path(section), :class => 'action edit') %>
        <%= link_to("Delete", delete_section_path(section), :class => 'action delete') %>
      </td>
    </tr>
    <% end%>
  </table>
</div>

app/views/sections/new.html.erb
<%= link_to("<<< Back to list", sections_path, :class => "back-link") %>

<div class="sections new">
  <h2> Create Section </h2>

  <%= form_for(@section) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

  <div class="form-buttons">
    <%= f.submit("Create Section") %>
  </div>

  <% end %>

</div>

app/views/sections/show.html.erb
<% if !flash[:notice].blank? %>
<div class = "notice">
  <%= flash[:notice] %>
</div>
<%end%>

<%= link_to("<< Back to pages list", pages_path, :class => "back-link") %>
<div class = "sections show">
  <h2> Sections </h2>

  <table>
    <tr>
      <th> Page ID</th>
      <td> <%= @section.page_id %> </td>
    </tr>

    <tr>
      <th>Name</th>
      <td> <%= @section.name %> </td>
    </tr>

    <tr>
      <th> Position </th>
      <td> <%= @section.position %> </td>
    </tr>

    <tr>
      <th> Visible </th>
      <td> <%= @section.visible ? 'true' : 'false' %> </td>
    </tr>

    <tr>
      <th> Content type </th>
      <td> <%= @section.content_type %> </td>
    </tr>

    <tr>
      <th> Contents </th>
      <td> <%= @section.content %> </td>
    </tr>
  </table>