config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  get 'subjects/index'
  get 'demo/hello'
  get 'pages/blog'
  get 'demo/escape_output'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary = "Page form fields">

  <tr>
    <th> Name </th>
    <td> <%= f.text_field(:name) %> </td>
  </tr>

  <tr>
    <th> Subject_id </th>
    <td> <%= f.select(:subject_id, @subjects.map {|s| [s.name, s.id]}) %></td>
  </tr>

  <tr>
    <th> Permalink </th>
    <td> <%= f.text_field(:permalink) %> </td>
  </tr>

  <tr>
    <th> Position </th>
    <td> <%= f.select(:position, 1..@page_count) %> </td>
  </tr>

  <tr>
    <th> Visible </th>
    <td> <%= f.check_box(:visible) %></td>
  </tr>


</table>

app/views/pages/blog.html.erb
<!DOCTYPE html>

<%= link_to('<< Back to Subjects', subjects_path, :class => "back-link") %>
<html>

	<head>

		<title>My Blog</title>

		<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">

	</head>



	<body>

		<!-- header start -->

		<div id="header" class="section">

			<p> <img alt="" class="img-circle" src="https://code.sololearn.com/Icons/Avatars/0.jpg"> </p>

			<p> Fady S. </p>

		</div>

		<!-- header end -->



		<!-- About Me section start -->

		<div id="main" class="section">

			<h1><span>About Me</span></h1>

			<p>

				Hey! I'm <strong>Alex</strong>. Coding has changed my world. It's not just about apps. Learning to code gave me <i>problem-solving skills</i> and a way to communicate with others on a technical level. I can also develop websites and use my coding skills to get a better job. And I learned it all at <strong>SoloLearn</strong> where they build your self-esteem and keep you motivated. Join me in this rewarding journey. You'll have fun, get help, and learn along the way!

			</p>

			<p class="quote" align="center">"Declare variables, not war"</p>

		</div>

		<!-- About Me section end -->



		<!-- My Schedule section start -->

		<div class="section">

			<h1><span>My Coding Schedule</span></h1>

			<table>

				<tr>

					<th>Day</th>

					<th>Mon</th>

					<th>Tue</th>

					<th>Wed</th>

					<th>Thu</th>

					<th>Fri</th>

				</tr>

				<tr>

					<td>8-8:30</td>

					<td class="selected">Learn</td>

					<td></td>

					<td></td>

					<td></td>

					<td></td>

				</tr>

				<tr>

					<td>9-10</td>

					<td></td>

					<td class="selected">Practice</td>

					<td></td>

					<td></td>

					<td></td>

				</tr>

				<tr>

					<td>1-1:30</td>

					<td></td>

					<td></td>

					<td class="selected">Play</td>

					<td></td>

					<td></td>

				</tr>

				<tr>

					<td>3:45-5</td>

					<td></td>

					<td></td>

					<td></td>

					<td class="selected">Code</td>

					<td></td>

				</tr>

				<tr>

					<td>6-6:15</td>

					<td></td>

					<td></td>

					<td></td>

					<td></td>

					<td class="selected">Discuss</td>

				</tr>

			</table>

		</div>

		<!-- My Schedule section end -->





		<!-- My Skills section start -->

		<div class="section">

			<h1><span>My Skills</span></h1>

			<ul>

				<li>HTML <br />

					<progress min="0" max="100" value="80"></progress>

				</li>

				<li>JavaScript <br />

					<progress min="0" max="100" value="50"></progress>

				</li>

				<li>Python <br />

					<progress min="0" max="100" value="30"></progress>

				</li>

			</ul>

		</div>

		<!-- My Skills section end -->





		<!-- Media section start -->

		<div class="section">

			<h1><span>My Media</span></h1>

			<iframe height="150" width="300" src="https://www.youtube.com/embed/Q6_5InVJZ88" allowfullscreen frameborder="0"></iframe>

		</div>

		<!-- Media section end -->



		<!-- Form section start -->

	  <div class="section">

			<h1><span>Contact Me</span></h1>



			<svg class="face" height="100" width="100">

				<circle cx="50" cy="50" r="50" fill="#FDD835"/>

				<circle cx="30" cy="30" r="10" fill="#FFFFFF"/>

				<circle cx="70" cy="30" r="10" fill="#FFFFFF"/>

				<circle cx="30" cy="30" r="5" fill="#000000"/>

				<circle cx="70" cy="30" r="5" fill="#000000"/>

				<path d="M 30 70 q 20 20 40 0" stroke="#FFFFFF" stroke-width="5" fill="none" />

			</svg>



			<form>

				<input name="name" placeholder="Name" type="text" required /><br/>

				<input name="email" placeholder="Email" type="email" required /><br/>

				<textarea name="message" placeholder="Message" required ></textarea>

				<input type="submit" value="SEND" class="submit" />

			</form>

		</div>

		<!-- Form section end -->



		<!-- Contacts section start -->

		<div class="section" id="contacts">

			<h1><span>Follow Me</span></h1>

			<div>

				<a href="https://www.sololearn.com/" target="_blank">

					<img alt="SoloLearn" src="https://www.sololearn.com/Uploads/icons/sololearn.png" />

				</a>

				<a href="#">

					<img alt="Facebook" src="https://www.sololearn.com/Uploads/icons/facebook.png"/>

				</a>

				<a href="#">

					<img alt="Twitter" src="https://www.sololearn.com/Uploads/icons/twitter.png" />

				</a>

			</div>

		</div>

		<!-- Contacts section end -->



		<div class="copyright">

			&copy; 2017 My Blog. All rights reserved.

		</div>



	</body>

</html>

app/views/pages/delete.html.erb
<%= link_to("<<< Back to Pages list", pages_path, :class => "back-link") %>

<div class="Page delete">
  <h2>Delete Page </h2>

  <%= form_for(@page, :method => 'delete') do |f| %>

    <p> Are you sure you want to permanently delete this page? </p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>

  <% end %>

</div>

app/views/pages/edit.html.erb
<%= link_to("<<< Back to Pages list", pages_path, :class => "back-link") %>

<div class="Page edit">
  <h2> Edit Page </h2>

  <%= form_for(@page) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f})%>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<% if !flash[:notice].blank? %>

  <div class="notice">
    <%= flash[:notice] %>
  </div>

<% end %>

<%= link_to("Fady's HTML blog", "/pages/blog", :class =>"blog" ) %>

<!-- Same in HTML -->
<br>
<br>

<a href="/pages/blog">Fady's Blog </a>


<div class="Pages index">
  <h2><b>Pages</b></h2>
  <p>
    <%= link_to("<< Back to subjects list", subjects_path, :class => 'back-link') %> </br>
    <br>
    <%= link_to("Add new page", new_page_path, :class => 'action new') %>

  </p>

  <table class="listing" summary="Page list">
    <tr class="header">
      <th> # </th>
      <th> Page </th>
      <th> Subject_id </th>
      <th> Permalink </th>
      <th> Visible </th>
      <th> Sections </th>
      <th> Actions </th>

    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %></td>
      <td><%= page.name %></td>
      <td><%= page.subject_id %></td>
      <td><%= page.permalink %></td>
      <td class="center"> <%= status_tag(page.visible) %> </td>
      <td class="center"> <%= page.sections.size %> </td>
      <td class="actions">
        <%= link_to("Show", page_path(page), :class => 'action show') %>
        <%= link_to("Edit", edit_page_path(page), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page), :class => 'action delete') %>
        <%= link_to("Sections", sections_path, :class => 'action show') %>

      </td>

    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<div class="Pages new">
  <h2> Create Page </h2>

  <%= form_for(@page) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f})%>

    <div class = "form-buttons">
      <%= f.submit("Create Page") %>

    </div>


  <% end %>
</div>

app/views/pages/show.html.erb
<%= link_to("<< Back to subjects list", subjects_path, :class => 'back-link') %></br>

<%= link_to("<< Back to pages list", pages_path, :class => 'back-link') %>

<div class= "pages show">
  <h2> Show Page </h2>

  <table summary = "Page detail view">
    <tr>
      <th> Name </th>
      <td> <%= @page.name %> </td>
    </tr>

    <tr>
      <th> Position </th>
      <td> <%= @page.position %> </td>
    </tr>

    <tr>
      <th> Permalink </th>
      <td> <%= @page.permalink %> </td>
    </tr>

    <tr>
      <th> Visible </th>
      <td> <%= @page.visible ? "Yes" : "No" %> </td>
    </tr>

    <tr>
      <th> Created </th>
      <td> <%= @page.created_at %> </td>
    </tr>

    <tr>
      <th> Updated </th>
      <td> <%= @page.updated_at %> </td>
    </tr>
  </table>

</div>